
// Objective-C API for talking to the following Go packages
//
//	alrd/alrdframework
//
// File is generated by gomobile bind. Do not edit.
#ifndef __Alrdframework_FRAMEWORK_H__
#define __Alrdframework_FRAMEWORK_H__

#include "Alrdframework.objc.h"
#include "Universe.objc.h"

#endif
